[package]
name = "yukikaze"
version = "0.2.0"
authors = ["gyara <me@gyara.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
log = "0.4.13"
reqwest = { version = "0.11.0", features = ["json"] }
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"
telegram_types = "0.5.0"
tokio = { version = "1.0.2", features = ["full"] }
warp = "0.3.0"
