[package]
name = "yukikaze"
version = "0.2.0"
authors = ["gyara <me@gyara.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.13"
log-panics = "2.0.0"
reqwest = { version = "0.11.0", features = ["json", "rustls-tls"], default-features=false }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
stackdriver_logger = "0.8.0"
telegram_types = "0.5.0"
tokio = { version = "1.0.2", features = ["rt", "rt-multi-thread"] }
warp = "0.3.0"
